import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-white`} style={{ background: '#234', border: '2px solid red', minHeight: '100vh'}}>
      <section className="container mx-auto w-75">
        {children}
        </section>
      </body>
    </html>
  )
}
